### ISSUE TITLE
Get-AteraAgents returns multiples when running on local system

### ISSUE THREAD

**Issue by aschleic1** [davejlong/PSAtera#11]
When calling Get-AteraAgents on a local system multiple items are returned if the system machinename is used by another agent.  

Example if you have two servers called "Server2016" and run Get-AteraAgents on one system you will get both returned and not just the system making the call.

Can AgentID be used so that only the matching system the PS Script is running on is returned?

**Comment by MisterDuval** [comment]
I'm looking with support for a way to get that agentID, but it is not a clear text in registry, so for now, that's not easy!

**Comment by MisterDuval** [comment]
Until Atera provides a way to get access to AgentId, encrypted in 
`HKEY_LOCAL_MACHINE\SOFTWARE\ATERA Networks\AlphaAgent\AgentId`
I'm filtering the multiple results with current's computer serial number
