### ISSUE TITLE
New-AteraAlert

### ISSUE THREAD

**Issue by DirectITServicesUK** [davejlong/PSAtera#13]
New-AteraAlert 

Example:-
`Get-AteraAgent | New-AteraAlert -Title "SFC Result" -Severity Information -AlertCategoryID General -AlertMessage "SFC did not find any integrity violations." `
The "-alertmessage" doesn't work and never arrives.

**Comment by MisterDuval** [comment]
AlertMessage is no longer available on the API
https://app.atera.com/apidocs#!/Alert/Alert_Post
I'll make a PR to remove it.
