### ISSUE TITLE
Install-AteraAgent

### ISSUE THREAD

**Issue by JacobErnst98** [davejlong/PSAtera#3]
I've written some code to install the Atera agent and noticed you have as well in https://github.com/davejlong/atera-scripts/blob/master/000Install-AteraAgent.ps1
I think this module could benefit from that function. Any reason you have kept them separate?

**Comment by davejlong** [comment]
No reason. I hadn't really thought about that. to be honest, I was just this morning starting to think about what I'd want included in PSAtera after support for all of the API endpoints is built out and I think it makes sense to add an Install script along. This also makes me think about how interesting it would be to have a pseudo script manager built in, so you could use it to execute other scripts from a public repository like davejlong/atera-scripts. For example, something like:

```
Execute-Script -Path "Printing/Clear-PrintQueue.ps1" -Repository "davejlong/atera-scripts"
```

**Comment by davejlong** [comment]
Added in v1.3.2
