### ISSUE TITLE
Problems using Get-AteraAgent and Set-AteraCustomValue

### ISSUE THREAD

**Issue by jensskov** [davejlong/PSAtera#6]
Hi

If I run Get-AteraAgent without any parameters I'm getting an error that parameters are missing. As I understand it, it should return the current Agent info. 

If I use Set-AteraCustomValue I get another error. I don't know if I use it wrong. The are some errors in the docs as it seems to be cut and paste from Get-AteraCustomValue. 

I get:
Set-AteraCustomValue -ObjectType Agent -ObjectID $agent.AgentID -FieldName $FieldName -Value "$biosinfo"
Invoke-RestMethod : 
404 - File or directory not found.
Server Error
 
  404 - File or directory not found.
  The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.
 
At C:\Program Files\WindowsPowerShell\Modules\PSAtera\1.5.2\PSAtera.psm1:113 char:11
+   $data = Invoke-RestMethod -Uri $Uri -Method "Put" -Headers $Headers ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by davejlong** [comment]
Sorry. Misread things. The issues with Set-AteraCustomValue should be fixed in the 1.5.4 release. Confirmed that there is an issue with the Get-AteraAgent cmdlet.

**Comment by davejlong** [comment]
Fixed in version 1.5.5.
