### ISSUE TITLE
Get-AteraAgents caps at 1000 objects

### ISSUE THREAD

**Issue by essiATanicura** [davejlong/PSAtera#9]
Is this a feature or a bug, and is there a way to get around it?

**Comment by eaglexeye69** [comment]
Found the same problem. You have to use Set-AteraRecordLimit.

You can check if it was successful via Get-AteraRecordLimit.

**Comment by davejlong** [comment]
The Set-AreraRecordLimit command can be used to override this setting for
the duration of the session.

**Comment by essiATanicura** [comment]
Thank you for both answers!
